export const ACTION_TYPE = {
    SET_USER:'SET_USER',
    LOGOUT: 'LOGOUT',
    SET_PRODUCT_DATA: 'SET_PRODUCT_DATA',
    SET_CATEGORY_DATA: 'SET_CATEGORY_DATA',
    RESET_PRODUCT_DATA: 'RESET_PRODUCT_DATA',
    RESET_CATEGORY_DATA: 'RESET_CATEGORY_DATA',
};

