
interface ActionTypes {
    SET_USER: string
    LOGOUT: string
    SET_PRODUCT_DATA: string
    SET_CATEGORY_DATA: string
    RESET_PRODUCT_DATA: string
    RESET_CATEGORY_DATA: string
}
export const ACTION_TYPES: ActionTypes = {
    SET_USER: 'SET_USER',
    LOGOUT: 'LOGOUT',
    SET_PRODUCT_DATA: 'SET_PRODUCT_DATA',
    SET_CATEGORY_DATA: 'SET_CATEGORY_DATA',
    RESET_PRODUCT_DATA: 'RESET_PRODUCT_DATA',
    RESET_CATEGORY_DATA: 'RESET_CATEGORY_DATA',
};

